In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv("glaucoma.csv")

In [4]:
df.head()

,Patient ID,Age,Gender,Visual Acuity Measurements,Intraocular Pressure (IOP),Cup-to-Disc Ratio (CDR),Family History,Medical History,Medication Usage,Visual Field Test Results,Optical Coherence Tomography (OCT) Results,Pachymetry,Cataract Status,Angle Closure Status,Visual Symptoms,Diagnosis,Glaucoma Type
0,62431,69,Male,LogMAR 0.1,19.46,0.42,No,Diabetes,"Amoxicillin, Lisinopril, Omeprazole, Atorvasta...","Sensitivity: 0.54, Specificity: 0.75","RNFL Thickness: 86.48 µm, GCC Thickness: 64.14...",541.51,Present,Open,"Tunnel vision, Eye pain, Nausea",No Glaucoma,Primary Open-Angle Glaucoma
1,68125,69,Female,LogMAR 0.1,18.39,0.72,No,Hypertension,"Lisinopril, Amoxicillin, Atorvastatin, Ibuprof...","Sensitivity: 0.72, Specificity: 0.88","RNFL Thickness: 96.88 µm, GCC Thickness: 56.48...",552.77,Absent,Open,"Redness in the eye, Vision loss, Tunnel vision",No Glaucoma,Juvenile Glaucoma
2,63329,67,Female,20/40,23.65,0.72,No,Hypertension,"Amoxicillin, Ibuprofen, Metformin, Atorvastati...","Sensitivity: 0.56, Specificity: 0.8","RNFL Thickness: 89.81 µm, GCC Thickness: 59.05...",573.65,Absent,Closed,"Halos around lights, Vision loss, Redness in t...",No Glaucoma,Juvenile Glaucoma
3,47174,23,Male,LogMAR 0.0,18.04,0.61,No,NaN,"Ibuprofen, Aspirin","Sensitivity: 0.6, Specificity: 0.93","RNFL Thickness: 87.25 µm, GCC Thickness: 63.98...",590.67,Absent,Closed,"Nausea, Nausea, Halos around lights",No Glaucoma,Congenital Glaucoma
4,67361,21,Male,LogMAR 0.1,15.87,0.30,No,Diabetes,"Amoxicillin, Omeprazole, Aspirin, Ibuprofen, A...","Sensitivity: 0.82, Specificity: 0.9","RNFL Thickness: 82.61 µm, GCC Thickness: 66.01...",588.41,Absent,Closed,"Eye pain, Eye pain, Tunnel vision",No Glaucoma,Primary Open-Angle Glaucoma

In [5]:
df.tail()

,Patient ID,Age,Gender,Visual Acuity Measurements,Intraocular Pressure (IOP),Cup-to-Disc Ratio (CDR),Family History,Medical History,Medication Usage,Visual Field Test Results,Optical Coherence Tomography (OCT) Results,Pachymetry,Cataract Status,Angle Closure Status,Visual Symptoms,Diagnosis,Glaucoma Type
9995,61720,81,Female,LogMAR 0.1,22.83,0.49,No,NaN,NaN,"Sensitivity: 0.81, Specificity: 0.97","RNFL Thickness: 83.41 µm, GCC Thickness: 66.55...",576.53,Absent,Open,"Eye pain, Eye pain, Tunnel vision",Glaucoma,Normal-Tension Glaucoma
9996,34983,65,Male,LogMAR 0.0,11.72,0.54,No,Diabetes,Lisinopril,"Sensitivity: 0.7, Specificity: 0.97","RNFL Thickness: 83.04 µm, GCC Thickness: 63.24...",548.10,Absent,Open,"Eye pain, Halos around lights, Vomiting",No Glaucoma,Normal-Tension Glaucoma
9997,67810,56,Female,20/40,10.67,0.56,Yes,Diabetes,Ibuprofen,"Sensitivity: 0.8, Specificity: 0.9","RNFL Thickness: 95.93 µm, GCC Thickness: 59.78...",513.74,Present,Open,"Vision loss, Vomiting, Blurred vision",No Glaucoma,Secondary Glaucoma
9998,34285,26,Male,LogMAR 0.1,23.37,0.74,No,Glaucoma in family,NaN,"Sensitivity: 0.68, Specificity: 0.9","RNFL Thickness: 92.84 µm, GCC Thickness: 69.35...",585.03,Absent,Closed,"Halos around lights, Nausea, Nausea",Glaucoma,Normal-Tension Glaucoma
9999,85320,76,Male,LogMAR 0.0,22.90,0.50,No,Diabetes,"Lisinopril, Ibuprofen, Amoxicillin","Sensitivity: 0.87, Specificity: 0.73","RNFL Thickness: 88.77 µm, GCC Thickness: 58.74...",510.10,Absent,Open,"Eye pain, Eye pain, Halos around lights",Glaucoma,Juvenile Glaucoma

In [6]:
df.shape

(10000, 17)

In [7]:
df.columns

Index(['Patient ID', 'Age', 'Gender', 'Visual Acuity Measurements',
       'Intraocular Pressure (IOP)', 'Cup-to-Disc Ratio (CDR)',
       'Family History', 'Medical History', 'Medication Usage',
       'Visual Field Test Results',
       'Optical Coherence Tomography (OCT) Results', 'Pachymetry',
       'Cataract Status', 'Angle Closure Status', 'Visual Symptoms',
       'Diagnosis', 'Glaucoma Type'],
      dtype='object')

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.isnull().sum()

Patient ID                                       0
Age                                              0
Gender                                           0
Visual Acuity Measurements                       0
Intraocular Pressure (IOP)                       0
Cup-to-Disc Ratio (CDR)                          0
Family History                                   0
Medical History                               2547
Medication Usage                              1231
Visual Field Test Results                        0
Optical Coherence Tomography (OCT) Results       0
Pachymetry                                       0
Cataract Status                                  0
Angle Closure Status                             0
Visual Symptoms                                  0
Diagnosis                                        0
Glaucoma Type                                    0
dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Patient ID                                  10000 non-null  int64
 1   Age                                         10000 non-null  int64
 2   Gender                                      10000 non-null  object
 3   Visual Acuity Measurements                  10000 non-null  object
 4   Intraocular Pressure (IOP)                  10000 non-null  float64
 5   Cup-to-Disc Ratio (CDR)                     10000 non-null  float64
 6   Family History                              10000 non-null  object
 7   Medical History                             7453 non-null   object
 8   Medication Usage                            8769 non-null   object
 9   Visual Field Test Results                   10000 non-null  object
 10  Optical Coherence Tomography (OCT) Results  10000 non-null  object
 11  Pachymetry                                  10000 non-null  float64
 12  Cataract Status                             10000 non-null  object
 13  Angle Closure Status                        10000 non-null  object
 14  Visual Symptoms                             10000 non-null  object
 15  Diagnosis                                   10000 non-null  object
 16  Glaucoma Type                               10000 non-null  object
dtypes: float64(3), int64(2), object(12)
memory usage: 1.3+ MB

In [11]:
df.describe()

,Patient ID,Age,Intraocular Pressure (IOP),Cup-to-Disc Ratio (CDR),Pachymetry
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000
mean,50002.16880,53.872200,17.507527,0.548437,549.733974
std,28939.82498,21.127563,4.356101,0.144326,28.902741
min,4.00000,18.000000,10.000000,0.300000,500.010000
25%,24660.25000,36.000000,13.760000,0.420000,524.590000
50%,50091.50000,54.000000,17.485000,0.550000,549.335000
75%,74829.25000,72.000000,21.300000,0.670000,574.972500
max,99992.00000,90.000000,25.000000,0.800000,599.990000

In [12]:
df.nunique()

Patient ID                                    10000
Age                                              73
Gender                                            2
Visual Acuity Measurements                        4
Intraocular Pressure (IOP)                     1499
Cup-to-Disc Ratio (CDR)                          51
Family History                                    2
Medical History                                   3
Medication Usage                               4079
Visual Field Test Results                      1574
Optical Coherence Tomography (OCT) Results    10000
Pachymetry                                     6343
Cataract Status                                   2
Angle Closure Status                              2
Visual Symptoms                                 512
Diagnosis                                         2
Glaucoma Type                                     6
dtype: int64

In [38]:
def classify_features(df):
    categorical_features = []
    non_categorical_features = []
    discrete_features = []
    continuous_features = []

    for column in df.columns:
        if df[column].dtype == 'object':
            if df[column].nunique() < 30:
                categorical_features.append(column)
            else:
                non_categorical_features.append(column)
        elif df[column].dtype in ['int64', 'float64']: # here 64 is the 64 bit Operating System
            if df[column].nunique() < 30:
                discrete_features.append(column)
            else:
                continuous_features.append(column)

    return categorical_features, non_categorical_features, discrete_features, continuous_features

In [39]:
categorical, non_categorical, discrete, continuous = classify_features(df)

In [35]:
print("Categorical Features:", categorical)
print("Non-Categorical Features:", non_categorical)
print("Discrete Features:", discrete)
print("Continuous Features:", continuous)

Categorical Features: ['Gender', 'Visual Acuity Measurements', 'Family History', 'Medical History', 'Cataract Status', 'Angle Closure Status', 'Diagnosis', 'Glaucoma Type']
Non-Categorical Features: ['Medication Usage', 'Visual Field Test Results', 'Optical Coherence Tomography (OCT) Results', 'Visual Symptoms']
Discrete Features: []
Continuous Features: ['Patient ID', 'Age', 'Intraocular Pressure (IOP)', 'Cup-to-Disc Ratio (CDR)', 'Pachymetry']

In [16]:
# Fill missing values in 'Sleep Disorder' with the mode
df['Medical History'] = df['Medical History'].fillna(df['Medical History'].mode()[0])

# Optional: check if any missing values remain
print("Missing values after filling:", df['Medical History'].isnull().sum())

Missing values after filling: 0

In [17]:
# Fill missing values in 'Sleep Disorder' with the mode
df['Medication Usage'] = df['Medication Usage'].fillna(df['Medication Usage'].mode()[0])

# Optional: check if any missing values remain
print("Missing values after filling:", df['Medication Usage'].isnull().sum())

Missing values after filling: 0

In [18]:
df.isnull().sum()

Patient ID                                    0
Age                                           0
Gender                                        0
Visual Acuity Measurements                    0
Intraocular Pressure (IOP)                    0
Cup-to-Disc Ratio (CDR)                       0
Family History                                0
Medical History                               0
Medication Usage                              0
Visual Field Test Results                     0
Optical Coherence Tomography (OCT) Results    0
Pachymetry                                    0
Cataract Status                               0
Angle Closure Status                          0
Visual Symptoms                               0
Diagnosis                                     0
Glaucoma Type                                 0
dtype: int64

In [32]:
df = df.drop(['Patient ID'],axis = 1)

In [40]:
print("Categorical Features:", categorical)
print("Non-Categorical Features:", non_categorical)
print("Discrete Features:", discrete)
print("Continuous Features:", continuous)

Categorical Features: ['Gender', 'Visual Acuity Measurements', 'Family History', 'Medical History', 'Cataract Status', 'Angle Closure Status', 'Diagnosis', 'Glaucoma Type']
Non-Categorical Features: []
Discrete Features: []
Continuous Features: ['Age', 'Intraocular Pressure (IOP)', 'Cup-to-Disc Ratio (CDR)', 'Pachymetry']

In [42]:
# Create a copy of the DataFrame with only the selected columns
df_selected = df.copy()

In [43]:
# Encode categorical features using one-hot encoding
df_encoded = pd.get_dummies(df_selected, columns=['Gender', 'Visual Acuity Measurements', 'Family History', 'Medical History', 'Cataract Status', 'Angle Closure Status', 'Diagnosis'])

In [44]:
from sklearn.preprocessing import MinMaxScaler
scaler =MinMaxScaler()
df[['Age', 'Intraocular Pressure (IOP)', 'Cup-to-Disc Ratio (CDR)', 'Pachymetry']]=scaler.fit_transform(df[['Age', 'Intraocular Pressure (IOP)', 'Cup-to-Disc Ratio (CDR)', 'Pachymetry']])

In [46]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df_encoded['Glaucoma Type'] = label_encoder.fit_transform(df_encoded['Glaucoma Type'])

In [47]:
df_encoded.columns

Index(['Age', 'Intraocular Pressure (IOP)', 'Cup-to-Disc Ratio (CDR)',
       'Pachymetry', 'Glaucoma Type', 'Gender_Female', 'Gender_Male',
       'Visual Acuity Measurements_20/20', 'Visual Acuity Measurements_20/40',
       'Visual Acuity Measurements_LogMAR 0.0',
       'Visual Acuity Measurements_LogMAR 0.1', 'Family History_No',
       'Family History_Yes', 'Medical History_Diabetes',
       'Medical History_Glaucoma in family', 'Medical History_Hypertension',
       'Cataract Status_Absent', 'Cataract Status_Present',
       'Angle Closure Status_Closed', 'Angle Closure Status_Open',
       'Diagnosis_Glaucoma', 'Diagnosis_No Glaucoma'],
      dtype='object')

In [48]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

In [58]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from imblearn.over_sampling import RandomOverSampler

X = df_encoded.drop('Glaucoma Type', axis=1)
y = df_encoded['Glaucoma Type']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)


print("Before Oversampling:", y_train.value_counts())

Before Oversampling: Glaucoma Type
2    1387
3    1359
4    1334
5    1326
1    1313
0    1281
Name: count, dtype: int64

In [59]:
df

,Age,Gender,Visual Acuity Measurements,Intraocular Pressure (IOP),Cup-to-Disc Ratio (CDR),Family History,Medical History,Pachymetry,Cataract Status,Angle Closure Status,Diagnosis,Glaucoma Type
0,0.708333,Male,LogMAR 0.1,0.630667,0.24,No,Diabetes,0.415083,Present,Open,No Glaucoma,Primary Open-Angle Glaucoma
1,0.708333,Female,LogMAR 0.1,0.559333,0.84,No,Hypertension,0.527706,Absent,Open,No Glaucoma,Juvenile Glaucoma
2,0.680556,Female,20/40,0.910000,0.84,No,Hypertension,0.736547,Absent,Closed,No Glaucoma,Juvenile Glaucoma
3,0.069444,Male,LogMAR 0.0,0.536000,0.62,No,Glaucoma in family,0.906781,Absent,Closed,No Glaucoma,Congenital Glaucoma
4,0.041667,Male,LogMAR 0.1,0.391333,0.00,No,Diabetes,0.884177,Absent,Closed,No Glaucoma,Primary Open-Angle Glaucoma
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0.875000,Female,LogMAR 0.1,0.855333,0.38,No,Glaucoma in family,0.765353,Absent,Open,Glaucoma,Normal-Tension Glaucoma
9996,0.652778,Male,LogMAR 0.0,0.114667,0.48,No,Diabetes,0.480996,Absent,Open,No Glaucoma,Normal-Tension Glaucoma
9997,0.527778,Female,20/40,0.044667,0.52,Yes,Diabetes,0.137327,Present,Open,No Glaucoma,Secondary Glaucoma
9998,0.111111,Male,LogMAR 0.1,0.891333,0.88,No,Glaucoma in family,0.850370,Absent,Closed,Glaucoma,Normal-Tension Glaucoma
9999,0.805556,Male,LogMAR 0.0,0.860000,0.40,No,Diabetes,0.100920,Absent,Open,Glaucoma,Juvenile Glaucoma

In [60]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [61]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

In [62]:
logreg = LogisticRegression()

In [63]:
logreg.fit(X_train_resampled, y_train_resampled)

LogisticRegression()

In [64]:
y_pred = logreg.predict(X_test)

In [65]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.158

In [66]:
report = classification_report(y_test, y_pred)
print("Classification Report:")
print(report)

Classification Report:
              precision    recall  f1-score   support

           0       0.14      0.17      0.15       320
           1       0.20      0.18      0.19       328
           2       0.16      0.08      0.11       347
           3       0.13      0.15      0.14       340
           4       0.17      0.23      0.19       334
           5       0.15      0.15      0.15       331

    accuracy                           0.16      2000
   macro avg       0.16      0.16      0.16      2000
weighted avg       0.16      0.16      0.16      2000

In [67]:
from sklearn import svm
svc = svm.SVC()
svc.fit(X_train_resampled, y_train_resampled)

SVC()

In [68]:
y_pred = svc.predict(X_test)

In [69]:
report = classification_report(y_test, y_pred)
print("Classification Report:")
print(report)

Classification Report:
              precision    recall  f1-score   support

           0       0.15      0.12      0.13       320
           1       0.00      0.00      0.00       328
           2       0.19      0.03      0.06       347
           3       0.15      0.36      0.21       340
           4       0.00      0.00      0.00       334
           5       0.16      0.44      0.24       331

    accuracy                           0.16      2000
   macro avg       0.11      0.16      0.11      2000
weighted avg       0.11      0.16      0.11      2000

In [70]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.1575

In [71]:
import pickle
with open('logreg_model.pkl', 'wb') as file:
    pickle.dump(logreg, file)
print("Model saved as logreg_model.pkl")

Model saved as logreg_model.pkl