Heart Failure Prediction

![alt text](Heart.jpeg)

In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv('heart_failure_clinical_records.csv')

In [5]:
df.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,55.0,0,748,0,45,0,263358.03,1.3,137,1,1,88,0
1,65.0,0,56,0,25,0,305000.00,5.0,130,1,0,207,0
2,45.0,0,582,1,38,0,319000.00,0.9,140,0,0,244,0
3,60.0,1,754,1,40,1,328000.00,1.2,126,1,0,90,0
4,95.0,1,582,0,30,0,461000.00,2.0,132,1,0,50,1

In [6]:
df.tail()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
4995,45.0,0,582,1,55,0,543000.0,1.0,132,0,0,250,0
4996,60.0,1,582,0,30,1,127000.0,0.9,145,0,0,95,0
4997,95.0,1,112,0,40,1,196000.0,1.0,138,0,0,24,1
4998,65.0,1,160,1,20,0,327000.0,2.7,116,0,0,8,1
4999,40.0,0,244,0,45,1,275000.0,0.9,140,0,0,174,0

In [7]:
df.shape

(5000, 13)

In [8]:
df.columns

Index(['age', 'anaemia', 'creatinine_phosphokinase', 'diabetes',
       'ejection_fraction', 'high_blood_pressure', 'platelets',
       'serum_creatinine', 'serum_sodium', 'sex', 'smoking', 'time',
       'DEATH_EVENT'],
      dtype='object')

In [9]:
df.isnull().sum()

age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    0
ejection_fraction           0
high_blood_pressure         0
platelets                   0
serum_creatinine            0
serum_sodium                0
sex                         0
smoking                     0
time                        0
DEATH_EVENT                 0
dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       5000 non-null   float64
 1   anaemia                   5000 non-null   int64
 2   creatinine_phosphokinase  5000 non-null   int64
 3   diabetes                  5000 non-null   int64
 4   ejection_fraction         5000 non-null   int64
 5   high_blood_pressure       5000 non-null   int64
 6   platelets                 5000 non-null   float64
 7   serum_creatinine          5000 non-null   float64
 8   serum_sodium              5000 non-null   int64
 9   sex                       5000 non-null   int64
 10  smoking                   5000 non-null   int64
 11  time                      5000 non-null   int64
 12  DEATH_EVENT               5000 non-null   int64
dtypes: float64(3), int64(10)
memory usage: 507.9 KB

In [11]:
df.duplicated(). sum()

np.int64(3680)

In [12]:
df=df.drop_duplicates()

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
from imblearn.over_sampling import RandomOverSampler

In [14]:
df_dummies = pd.get_dummies(df,columns=['sex','smoking'], drop_first=True)

In [15]:
df_dummies

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,time,DEATH_EVENT,sex_1,smoking_1
0,55.0,0,748,0,45,0,263358.03,1.30,137,88,0,True,True
1,65.0,0,56,0,25,0,305000.00,5.00,130,207,0,True,False
2,45.0,0,582,1,38,0,319000.00,0.90,140,244,0,False,False
3,60.0,1,754,1,40,1,328000.00,1.20,126,90,0,True,False
4,95.0,1,582,0,30,0,461000.00,2.00,132,50,1,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4731,75.0,0,582,1,30,1,263358.03,1.83,134,23,1,True,False
4855,73.0,0,582,0,20,0,263358.03,1.83,134,198,1,True,True
4862,45.0,0,220,0,35,0,174000.00,0.80,139,121,0,True,True
4965,40.0,1,129,1,35,0,255000.00,0.90,137,209,0,True,False
4972,70.0,0,835,0,35,0,327000.00,1.10,142,245,0,False,False

In [16]:
scaler=MinMaxScaler()
df_dummies[['high_blood_pressure','platelets']] = scaler.fit_transform(df_dummies[['high_blood_pressure','platelets']])

In [17]:
df_dummies['DEATH_EVENT'].value_counts()

DEATH_EVENT
0    923
1    397
Name: count, dtype: int64

In [18]:
X = df_dummies.drop('DEATH_EVENT', axis=1)  
y = df_dummies['DEATH_EVENT']

In [19]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Before Oversampling:", y_train.value_counts())

Before Oversampling: DEATH_EVENT
0    738
1    318
Name: count, dtype: int64

In [20]:
ros = RandomOverSampler(random_state=42)
X_train_res, y_train_res = ros.fit_resample(X_train, y_train)

print("After Oversampling:\n", y_train_res.value_counts())

After Oversampling:
 DEATH_EVENT
0    738
1    738
Name: count, dtype: int64

In [21]:
log_reg = LogisticRegression(max_iter=1000, solver='liblinear')
log_reg.fit(X_train_res,y_train_res)

LogisticRegression(max_iter=1000, solver='liblinear')

In [22]:
y_pred = log_reg.predict(X_test)

In [23]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", conf_matrix)

# Classification Report
class_report = classification_report(y_test, y_pred)
print("\nClassification Report:\n", class_report)

Accuracy: 0.8106060606060606

Confusion Matrix:
 [[148  37]
 [ 13  66]]

Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.80      0.86       185
           1       0.64      0.84      0.73        79

    accuracy                           0.81       264
   macro avg       0.78      0.82      0.79       264
weighted avg       0.84      0.81      0.82       264