In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv('sleep_disorder.csv')

In [4]:
df.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.isnull().sum()

Person ID                    0
Gender                       0
Age                          0
Occupation                   0
Sleep Duration               0
Quality of Sleep             0
Physical Activity Level      0
Stress Level                 0
BMI Category                 0
Blood Pressure               0
Heart Rate                   0
Daily Steps                  0
Sleep Disorder             219
dtype: int64

In [7]:
df = df.drop(['Person ID'], axis = 1)

In [8]:
df.nunique()

Gender                      2
Age                        31
Occupation                 11
Sleep Duration             27
Quality of Sleep            6
Physical Activity Level    16
Stress Level                6
BMI Category                4
Blood Pressure             25
Heart Rate                 19
Daily Steps                20
Sleep Disorder              2
dtype: int64

In [9]:
df

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...
369,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [10]:
object_columns = df.select_dtypes(include=['object']).columns
print("Object type columns:")
print(object_columns)

numerical_columns = df.select_dtypes(include=['int64', 'float64']).columns
print("\nNumerical type columns:")
print(numerical_columns)

Object type columns:
Index(['Gender', 'Occupation', 'BMI Category', 'Blood Pressure',
       'Sleep Disorder'],
      dtype='object')

Numerical type columns:
Index(['Age', 'Sleep Duration', 'Quality of Sleep', 'Physical Activity Level',
       'Stress Level', 'Heart Rate', 'Daily Steps'],
      dtype='object')

In [11]:
def classify_features(df):
    categorical_features = []
    non_categorical_features = []
    discrete_features = []
    continuous_features = []

    for column in df.columns:
        if df[column].dtype == 'object':
            if df[column].nunique() < 30:
                categorical_features.append(column)
            else:
                non_categorical_features.append(column)
        elif df[column].dtype in ['int64', 'float64']: # here 64 is the 64 bit Operating System
            if df[column].nunique() < 30:
                discrete_features.append(column)
            else:
                continuous_features.append(column)

    return categorical_features, non_categorical_features, discrete_features, continuous_features

In [12]:
categorical, non_categorical, discrete, continuous = classify_features(df)

In [13]:
print("Categorical Features:", categorical)
print("Non-Categorical Features:", non_categorical)
print("Discrete Features:", discrete)
print("Continuous Features:", continuous)

Categorical Features: ['Gender', 'Occupation', 'BMI Category', 'Blood Pressure', 'Sleep Disorder']
Non-Categorical Features: []
Discrete Features: ['Sleep Duration', 'Quality of Sleep', 'Physical Activity Level', 'Stress Level', 'Heart Rate', 'Daily Steps']
Continuous Features: ['Age']

In [14]:
# Fill missing values in 'Sleep Disorder' with the mode
df['Sleep Disorder'] = df['Sleep Disorder'].fillna(df['Sleep Disorder'].mode()[0])

# Optional: check if any missing values remain
print("Missing values after filling:", df['Sleep Disorder'].isnull().sum())

Missing values after filling: 0

In [15]:
df.isnull().sum()

Gender                     0
Age                        0
Occupation                 0
Sleep Duration             0
Quality of Sleep           0
Physical Activity Level    0
Stress Level               0
BMI Category               0
Blood Pressure             0
Heart Rate                 0
Daily Steps                0
Sleep Disorder             0
dtype: int64

In [16]:
object_columns = df.select_dtypes(include=['object']).columns
print("Object type columns:")
print(object_columns)

numerical_columns = df.select_dtypes(include=['int64', 'float64']).columns
print("\nNumerical type columns:")
print(numerical_columns)

Object type columns:
Index(['Gender', 'Occupation', 'BMI Category', 'Blood Pressure',
       'Sleep Disorder'],
      dtype='object')

Numerical type columns:
Index(['Age', 'Sleep Duration', 'Quality of Sleep', 'Physical Activity Level',
       'Stress Level', 'Heart Rate', 'Daily Steps'],
      dtype='object')

In [17]:
print("Categorical Features:", categorical)
print("Non-Categorical Features:", non_categorical)
print("Discrete Features:", discrete)
print("Continuous Features:", continuous)

Categorical Features: ['Gender', 'Occupation', 'BMI Category', 'Blood Pressure', 'Sleep Disorder']
Non-Categorical Features: []
Discrete Features: ['Sleep Duration', 'Quality of Sleep', 'Physical Activity Level', 'Stress Level', 'Heart Rate', 'Daily Steps']
Continuous Features: ['Age']

In [18]:
# Encode categorical features except target
feature_cols = ['Gender', 'Occupation', 'BMI Category', 'Blood Pressure']
df = pd.get_dummies(df, columns=feature_cols, drop_first=False)

# Target encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(df['Sleep Disorder'])
X = df.drop('Sleep Disorder', axis=1)

In [19]:
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()
df[continuous]=scaler.fit_transform(df[continuous])

In [20]:
df

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps,Sleep Disorder,Gender_Female,Gender_Male,...,Blood Pressure_130/85,Blood Pressure_130/86,Blood Pressure_131/86,Blood Pressure_132/87,Blood Pressure_135/88,Blood Pressure_135/90,Blood Pressure_139/91,Blood Pressure_140/90,Blood Pressure_140/95,Blood Pressure_142/92
0,0.00000,6.1,6,42,6,77,4200,Sleep Apnea,False,True,...,False,False,False,False,False,False,False,False,False,False
1,0.03125,6.2,6,60,8,75,10000,Sleep Apnea,False,True,...,False,False,False,False,False,False,False,False,False,False
2,0.03125,6.2,6,60,8,75,10000,Sleep Apnea,False,True,...,False,False,False,False,False,False,False,False,False,False
3,0.03125,5.9,4,30,8,85,3000,Sleep Apnea,False,True,...,False,False,False,False,False,False,False,True,False,False
4,0.03125,5.9,4,30,8,85,3000,Sleep Apnea,False,True,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,1.00000,8.1,9,75,3,68,7000,Sleep Apnea,True,False,...,False,False,False,False,False,False,False,False,True,False
370,1.00000,8.0,9,75,3,68,7000,Sleep Apnea,True,False,...,False,False,False,False,False,False,False,False,True,False
371,1.00000,8.1,9,75,3,68,7000,Sleep Apnea,True,False,...,False,False,False,False,False,False,False,False,True,False
372,1.00000,8.1,9,75,3,68,7000,Sleep Apnea,True,False,...,False,False,False,False,False,False,False,False,True,False
373,1.00000,8.1,9,75,3,68,7000,Sleep Apnea,True,False,...,False,False,False,False,False,False,False,False,True,False

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from imblearn.over_sampling import RandomOverSampler

X = df.drop('Sleep Disorder', axis=1)
y = df['Sleep Disorder']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)


print("Before Oversampling:", y_train.value_counts())

Before Oversampling: Sleep Disorder
Sleep Apnea    237
Insomnia        62
Name: count, dtype: int64

In [22]:
ros = RandomOverSampler(random_state=42)
#we apply sampling on only train data
X_train_res, y_train_res = ros.fit_resample(X_train, y_train)

print("After Oversampling:", y_train_res.value_counts())

After Oversampling: Sleep Disorder
Sleep Apnea    237
Insomnia       237
Name: count, dtype: int64

In [23]:
log_reg = LogisticRegression(max_iter=1000, solver='liblinear')
log_reg.fit(X_train_res, y_train_res)

LogisticRegression(max_iter=1000, solver='liblinear')

In [24]:
y_pred = log_reg.predict(X_test)

In [25]:
print("\nAccuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.96

Confusion Matrix:
 [[14  1]
 [ 2 58]]

Classification Report:
               precision    recall  f1-score   support

    Insomnia       0.88      0.93      0.90        15
 Sleep Apnea       0.98      0.97      0.97        60

    accuracy                           0.96        75
   macro avg       0.93      0.95      0.94        75
weighted avg       0.96      0.96      0.96        75

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 50 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Age                              374 non-null    float64
 1   Sleep Duration                   374 non-null    float64
 2   Quality of Sleep                 374 non-null    int64
 3   Physical Activity Level          374 non-null    int64
 4   Stress Level                     374 non-null    int64
 5   Heart Rate                       374 non-null    int64
 6   Daily Steps                      374 non-null    int64
 7   Sleep Disorder                   374 non-null    object
 8   Gender_Female                    374 non-null    bool
 9   Gender_Male                      374 non-null    bool
 10  Occupation_Accountant            374 non-null    bool
 11  Occupation_Doctor                374 non-null    bool
 12  Occupation_Engineer              374 non-null    bool
 13  Occupation_Lawyer                374 non-null    bool
 14  Occupation_Manager               374 non-null    bool
 15  Occupation_Nurse                 374 non-null    bool
 16  Occupation_Sales Representative  374 non-null    bool
 17  Occupation_Salesperson           374 non-null    bool
 18  Occupation_Scientist             374 non-null    bool
 19  Occupation_Software Engineer     374 non-null    bool
 20  Occupation_Teacher               374 non-null    bool
 21  BMI Category_Normal              374 non-null    bool
 22  BMI Category_Normal Weight       374 non-null    bool
 23  BMI Category_Obese               374 non-null    bool
 24  BMI Category_Overweight          374 non-null    bool
 25  Blood Pressure_115/75            374 non-null    bool
 26  Blood Pressure_115/78            374 non-null    bool
 27  Blood Pressure_117/76            374 non-null    bool
 28  Blood Pressure_118/75            374 non-null    bool
 29  Blood Pressure_118/76            374 non-null    bool
 30  Blood Pressure_119/77            374 non-null    bool
 31  Blood Pressure_120/80            374 non-null    bool
 32  Blood Pressure_121/79            374 non-null    bool
 33  Blood Pressure_122/80            374 non-null    bool
 34  Blood Pressure_125/80            374 non-null    bool
 35  Blood Pressure_125/82            374 non-null    bool
 36  Blood Pressure_126/83            374 non-null    bool
 37  Blood Pressure_128/84            374 non-null    bool
 38  Blood Pressure_128/85            374 non-null    bool
 39  Blood Pressure_129/84            374 non-null    bool
 40  Blood Pressure_130/85            374 non-null    bool
 41  Blood Pressure_130/86            374 non-null    bool
 42  Blood Pressure_131/86            374 non-null    bool
 43  Blood Pressure_132/87            374 non-null    bool
 44  Blood Pressure_135/88            374 non-null    bool
 45  Blood Pressure_135/90            374 non-null    bool
 46  Blood Pressure_139/91            374 non-null    bool
 47  Blood Pressure_140/90            374 non-null    bool
 48  Blood Pressure_140/95            374 non-null    bool
 49  Blood Pressure_142/92            374 non-null    bool
dtypes: bool(42), float64(2), int64(5), object(1)
memory usage: 38.8+ KB